package lexer

enum class Token {
    PUBLIC_KEY_WORD,
    PRIVATE_KEY_WORD,
    FINAL_KEY_WORD,
    STRING_TYPE,
    INTEGER_TYPE,
    BOOLEAN_TYPE,
    COMPARISON_TYPE,
    OPERATOR_TYPE,
    ASSOCIATION,
    STRING,
    INTEGER,
    BOOLEAN,
    PLUS,
    MINUS,
    MULTIPLY,
    DIVIDE,
    OPEN_PARENTHESIS,
    CLOSE_PARENTHESIS,
    EQUALS,
    MINOR_EQUALS,
    MAJOR_EQUALS,
    NOT_EQUALS,
    LESS_THAN,
    GREATER_THAN,
    SEMICOLON
}